<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catan.Core\Catan.Core.csproj" />
    <ProjectReference Include="..\Catan.AI\Catan.AI.csproj" />
  </ItemGroup>

</Project>
